channels:
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - ipython=7.8.0
  - pip=19.3.1
  - python=3.6.9
  - setuptools=41.4.0
  - pip:
    - astropy==3.2.1
    - docutils==0.15.2
    - jwxml==0.3.0
    - matplotlib==3.1.1
    - numpy==1.17.3
    - photutils==0.6
    - poppy==0.8.0
    - pysiaf==0.6.1
    - pytest==5.0.1
    - scipy==1.3.1
    - six==1.12.0
    - sphinx==2.2.1